version: '3.7'

networks:
  outside:
    external: true
services:
  userservice:
    image: tom-messageservice:latest
    networks:
      - default
      - outside
    ports:
      - 8080:8080
    expose:
      - 8080